# example netlify.toml
[build]
  command = "pnpm --filter @awesome-alpine/www... run build"
  functions = "www/netlify/functions"
  publish = "www/dist"

[dev]
  command = "pnpm dev" # Command to start your dev server
  port = 4173 # Port that the dev server will be listening on
  publish = "dist" # Folder with the static content for _redirect file

[context.dev]
  environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }

[context.production.environment]
  NODE_VERSION = '20.7.0'
  AWS_LAMBDA_JS_RUNTIME = 'nodejs18.x'

[[redirects]]
  from ="/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from ="/*"
  to = "/.netlify/builders/builder/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
