// Generated by Wrangler on Fri Sep 06 2024 20:32:14 GMT+0400 (Gulf Standard Time)
// by running `wrangler types`

interface Env {
	PLAY_SHARE: KVNamespace;
	NODE_VERSION: "22.5.1";
	PNPM_VERSION: "9.6.0";
}
