// Generated by Wrangler on Sat Jul 27 2024 19:42:08 GMT+0400 (Gulf Standard Time)
// by running `wrangler types`

interface Env {
	PLAY_SHARE: KVNamespace;
	NODE_VERSION: "22.5.1";
	PNPM_VERSION: "9.6.0";
}
